version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend-nodejs
      - backend-fastapi

  backend-nodejs:
    build:
      context: .
      dockerfile: backend-nodejs/Dockerfile
    ports:
      - "3001:3001"

  backend-fastapi:
    build:
      context: .
      dockerfile: backend-fastapi/Dockerfile
    ports:
      - "8000:8000"
